# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8695f749ed61aa9aaba45a5ae876734e37476152b5960e640be9563a7dcea52b48ddcd6b09671d7a68f480b6cdfc2c8846cd1af0af3f98546a2549ffbe2f3f83

test:
  secret_key_base: 9c2f3468c64a1711b1dbcb7045363e534849b45086a91527066f7b47744e5ab37c198ad496222d35d89cbaad7deaed90b986e8e49ec4a57e7df2f22cf00aae45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
